spring.application.name=roles-backend

# PostgreSQL
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/datacom}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

# Initialization basada en SQL (solo crea tablas de ejemplo si no existen)
spring.sql.init.mode=never

server.port=8080
