// export const URL_API = "http://localhost:28181";
export const URL_API = "https://datacomdev.fodc.org.co:9443";
// export const URL_API = "http://192.168.1.16:28181";
// export const URL_API = "http://191.103.253.34:28181";
// export const URL_API = 'https://datacom-backend.herokuapp.com'

export const TOKEN_AUTH_USERNAME = "wang-plus";
export const TOKEN_AUTH_PASSWORD = "G3n0m4Plu51*!";

export const TIPO_ENCUESTA = {
  VIVIENDA: 1,
  COMUNIDAD: 2,
  MUNICIPIO: 3,
  JAC: 4
};

export const NIVEL_GERENCIAL = {
  JUNTA_DIRECTIVA: 246,
  COMITE_TRABAJO: 247
};

export const CATEGORIAS = {
  TIPOS_ESTUDIO: "TEST",
  SECRETARIAS_DE_GOBIERNO: "SGOB",
  POLITICAS_PUBLICAS: "PPUB",
  ORGANIZACIONES_DE_LA_COMUNIDAD: "ORGC",
  INFRAESTRUCTURA_PUBLICA: "INFP",
  FINANZAS_PUBLICAS: "FINP",
  MEDIOS_DE_COMUNICACION: "MEDC",
  VIAS_ACCESO: "VIAS",
  ECOSISTEMAS: "ECOS",
  INFRASALUD: "INSA",
  PROGRAMAS_INFANTILES: "PINF",
  NIVEL_INSTITUCION_EDUCATIVA: "NINS",
  DISPOSICION_EXCRETAS: "EXCR",
  DISPOSICION_RESIDUOS: "DISPO",
  CARGOS: "CARG",
  SERVICIOS_DE_SALUD: "SSAL",
  FRECUENCIA_SERVICIOS_SALUD: "FSSA",
  AREAS_UBICACION_VIVIENDAS: "AUVI",
  TENENCIA_VIVIENDA: "TEVI",
  MATERIAL_PAREDES: "MATP",
  MATERIAL_PISOS: "MAPI",
  MATERIAL_TECHO: "MATE",
  SERVICIOS_PUBLICOS: "SEPU",
  FECUENCIA_SERVICIO_ACUEDUCTO: "FREC",
  FUENTES_HIDRICAS: "FUCA",
  CAPACIDAD_ALMACENAMIENTO: "CAAL",
  ACTIVDADES_ECONOMICAS: "ACEC",
  PARTICIPACION_CIUDADANA: "PACI",
  TIPO_CONTRATO: "TICO",
  LINEA: "LINE",
  ESPACIO_PARTICIPACION: "ESPA",
  TEMAS_CAPACITACION: "TECA",
  TIPO_JUNTA: "TIJU",
  TIPO_DOCUMENTO_IDENTIDAD: "TDI",
  NIVEL_EDUCATIVO: "NE",
  SEXO: "SEXO",
  COMITES_TRABAJO: "COMTE",
  BANCO: "BANCO",
  CONTRATOS_PROYECTOS: "COPRO",
  LINEA_PROYECTOS: "LINPR",
  PARENTESCO: "PAREN",
  ETNIAS: "ETN",
  OCUPACION: "OCUP",
  SEGURIDAD_SOCIAL: "SS",
  NIVEL_INGRESOS: "NIIG",
  DISCAPACIDADES: "DISC",
  PROGRAMAS_SOCIALES: "PROGS",
  PRODUCTOS_VIVIENDA: "PRODV",
  TIPO_COMUNIDAD: "TICOM"
};

export const TEMAS_SEGUIMIENTO_JAC = {
  JUNTA_ADMINISTRADORA: 1,
  ASAMBLEA_SOCIOS: 2,
  DIRECCIONAMIENTO_ESTRATEGICO: 3,
  ADMINISTRATIVO: 4,
  FINANCIERO: 5,
  EJECUCION_PROYECTOS: 6,
  CAPACITACION: 7,
  PARTICIPACION: 8
};
