export const URL_API = 'http://localhost:28181'
// export const URL_API = 'http://192.168.0.136:28181'
// export const URL_API = 'http://191.103.253.34:28181'
// export const URL_API = 'https://datacom-backend.herokuapp.com'

export const TIPO_ENCUESTA = {
    VIVIENDA: 1,
    COMUNIDAD: 2,
    MUNICIPIO: 3,
    JAC: 4
}

export const CATEGORIAS = {
    TIPOS_ESTUDIO: 'TEST',
    SECRETARIAS_DE_GOBIERNO: 'SGOB',
    POLITICAS_PUBLICAS: 'PPUB',
    ORGANIZACIONES_DE_LA_COMUNIDAD: 'ORGC',
    INFRAESTRUCTURA_PUBLICA: 'INFP',
    FINANZAS_PUBLICAS: 'FINP',
    MEDIOS_DE_COMUNICACION: 'MEDC',
    VIAS_ACCESO: 'VIAS',
    ECOSISTEMAS: 'ECOS',
    INFRASALUD: 'INSA',
    PROGRAMAS_INFANTILES: 'PINF',
    NIVEL_INSTITUCION_EDUCATIVA: 'NINS',
    DISPOSICION_EXCRETAS: 'EXCR',
    CARGOS: 'CARG',
    SERVICIOS_DE_SALUD: 'SSAL',
    FRECUENCIA_SERVICIOS_SALUD: 'FSSA',
    ACTIVDADES_ECONOMICAS: 'ACEC',
  PARTICIPACION_CIUDADANA: 'PACI',
  TIPO_CONTRATO: 'TICO',
  LINEA: 'LINE',
  ESPACIO_PARTICIPACION: 'ESPA',
  TEMAS_CAPACITACION: 'TECA'
}
